Update

diff --git a/file/xunlei b/file/xunlei
--- a/file/xunlei
+++ b/file/xunlei
@@ -17,10 +17,9 @@ if [[ "$(id -u)" != "0" ]]; then
 fi
 
 # Xunlei defintions
-SCRIPT=/etc/init.d/xunlei
 DESC="Xunlei-Remote"
-PREFIX=/usr/local/xunlei
-BIN=portal
+SCRIPT=/opt/bin/xunlei
+PREFIX=/opt/xunlei
 DAEMON=${PREFIX}/portal
 CFG_DIR=${PREFIX}/cfg
 MOUNT_CFG=${CFG_DIR}/thunder_mounts.cfg
@@ -29,20 +28,6 @@ LIB_A=${LIB_DIR}/ETMDaemon
 LIB_B=${LIB_DIR}/EmbedThunderManager
 PID_FILE=${PREFIX}/xunlei.pid
 DOWNLOAD_URL=http://lazyzhu.com/file/xunlei_arm_le_armv5te.tar.gz
-
-# Check file/folder if exist
-[[ -f $DAEMON ]] && [[ -f $LIB_A ]] && [[ -f $LIB_B ]] || exit 3
-
-# Check folders
-[[ -d $CFG_DIR ]] || mkdir -p $CFG_DIR
-
-# Check file permissions
-[[ -x $DAEMON ]] || chmod +x $DAEMON
-[[ -x $LIB_A ]] || chmod +x $LIB_A
-[[ -x $LIB_B ]] || chmod +x $LIB_B
-
-# Check wget
-[[ -f /usr/bin/wget ]] || ln -s /bin/busybox /usr/bin/wget
 
 do_mounts_cfg() {
     echo "avaliable_mount_path_pattern" >$MOUNT_CFG
@@ -118,17 +103,37 @@ do_check() {
     LAN_IP=`ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`
     PORT=9000
     STATUS=`wget -t 3 -T 3 -qO- http://${LAN_IP}:${PORT}/getsysinfo`
-    echo $STATUS | grep "\[ 0, 1, 1, 1, \""
-    if [[ "$?" != "0" ]]; then
-        /etc/init.d/xunlei restart
+    echo $STATUS | grep "\[ 0, 1, 1, 1, \"" >/dev/null 2>&1
+    if [[ "$?" == "0" ]]; then
+        echo "$(date +"%Y-%m-%d_%T") $DESC looks ok."
+    else
+        do_restart
+        echo "$(date +"%Y-%m-%d_%T") $DESC goes error, try to restart."
     fi
 }
 
 do_setup() {
+    echo -e "\033[32m $DESC installing ... \033[0m"
     [[ -d $PREFIX ]] && rm -rf $PREFIX
     wget $DOWNLOAD_URL >/dev/null 2>&1
-    tar -zxvf xunlei_arm_le_armv5te.tar.gz -C /usr/local >/dev/null 2>&1
+    tar -zxvf xunlei_arm_le_armv5te.tar.gz -C /opt >/dev/null 2>&1
+    rm -rf xunlei_arm_le_armv5te.tar.gz
 }
+
+# Check file/folder if exist
+[[ -f $DAEMON ]] && [[ -f $LIB_A ]] && [[ -f $LIB_B ]] || do_setup
+
+# Check folders
+[[ -d $PREFIX ]] || mkdir -p $PREFIX
+[[ -d $CFG_DIR ]] || mkdir -p $CFG_DIR
+
+# Check file permissions
+[[ -x $DAEMON ]] || chmod +x $DAEMON
+[[ -x $LIB_A ]] || chmod +x $LIB_A
+[[ -x $LIB_B ]] || chmod +x $LIB_B
+
+# Check wget
+[[ -f /usr/bin/wget ]] || ln -s /bin/busybox /usr/bin/wget
 
 # See how we were called
 case "$1" in
@@ -151,7 +156,7 @@ case "$1" in
   do_setup
   ;;
   *)
-  echo -e "\033[36m Usage: $SCRIPT {start|stop|restart|status|setup} \033[0m"
+  echo -e "\033[36m Usage: $SCRIPT {start|stop|restart|status|check|setup} \033[0m"
   exit 4
   ;;
 esac
